# Copyright © 2022 Durudex

# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

name: Linter

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  go-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install Golang CI Lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.46.0
